export const LOGIN_ROUTE = '/login'
export const MAIN_ROUTE = '/'
export const REGISTRATION_ROUTE = '/registration'
export const TASKS_ROUTE = '/tasks'
export const LK_ROUTE = '/lk'
export const TASK_ROUTE = '/task/:id'