name: BuildAndPushDockerImage

on:
  push:
    branches: [ frontend ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        run: cd client && npm test

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v2

      - name: Build the react app
        run: cd client && npm ci --production

      - name: Build the Docker image
        run: docker build -t zeph1rrio/crowdecrypt:${{github.event.commits[0].message}}-SNAPSHOT .

      - name: Check images
        run: docker images | grep ${{github.event.commits[0].message}}

      - name: Login in docker
        run: docker login -u zeph1rrio -p ${{secrets.DOCKER_HUB_PASS}}

      - name: Push into registry
        run: docker push zeph1rrio/crowdecrypt:${{github.event.commits[0].message}}-SNAPSHOT
